ramadhan4kids/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     url(r'^admin/', include(admin.site.urls)),
     url(r'^', include('ramadhan4kidsapp.urls', namespace='ramadhan4kidsapp')),
]

ramadhan4kidsapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve as static_serve
from .views import admin_views, user_views

urlpatterns = [
     url(r'^admin/', include(admin.site.urls)),
     url(r'^administrasi/$', admin_views.index, name='admin.index'),
     url(r'^administrasi/upload-keuangan/$', admin_views.upload_pengeluaran_excel, name='admin.upload_laporan'),
     url(r'^administrasi/laporan-keuangan/$', admin_views.laporan_keuangan, name='admin.laporan_keuangan'),
     url(r'^administrasi/laporan-list/$', admin_views.laporan_list, name='admin.laporan_list'),
     url(r'^administrasi/add-laporan/$', admin_views.add_laporan, name='admin.add.laporan'),
     url(r'^administrasi/edit-laporan/(?P<id>\d+)/$', admin_views.edit_laporan, name='admin.edit.laporan'),
     url(r'^administrasi/kirim-lpj/$', admin_views.kirim_lpj, name='admin.kirim.lpj'),
     url(r'^administrasi/upload-data-donasi/$', admin_views.upload_donasi, name='admin.upload.donasi'),

     url(r'^$', user_views.index, name='user.index'),
     url(r'^login/$', login, name='login'),
     url(r'^logout/$', logout, {'next_page' : '/'}, name='logout'),
     url(r'^story/$', user_views.story, name='user.story'),
     url(r'^keranjang-donasi/$', user_views.keranjang, name='user.keranjang'),
     url(r'^add-item', user_views.add_item, name='user.add_item'),
     url(r'^konfirmasi-donasi/$', user_views.konfirmasi, name='user.konfirmasi'),
     url(r'^sukses/$', user_views.sukses_simpan_donasi, name='user.sukses'),
     url(r'^checkout-donasi/$', user_views.checkout, name='user.checkout'),
     url(r'^isi-identitas-donatur/$', user_views.isi_data, name='user.isi_data'),
     url(r'^remove-item-keranjang/$', user_views.remove_item_keranjang, name='user.remove'),
     

] + static(settings.DATA_URL, document_root=settings.DATA_ROOT)

ramadhan4kidsapp/models.py
from django.db import models

class Temp(models.Model):
    filecontent = models.FileField(upload_to='data/file_temp')

# Create your models here.
class PenerimaManfaat(models.Model):
    nama = models.CharField(max_length=100)
    pic = models.CharField(max_length=100)
    jumlah_anak = models.IntegerField(default=0)

class KategoriAnak(models.Model):
    kategori = models.IntegerField()
    keterangan = models.CharField(max_length=100)

class Anak(models.Model):
    kategori = models.ForeignKey(KategoriAnak)
    nama = models.CharField(max_length=100)
    umur = models.IntegerField()
    kelas = models.IntegerField()
    komunitas = models.ForeignKey(PenerimaManfaat)

# Create your models here.
class Bank(models.Model):
    nama_bank = models.CharField(max_length=100)
    nama_pemilik_rek = models.CharField(max_length=100)
    no_rekening = models.CharField(max_length=100)
    program = models.ForeignKey('Program', null=True)
    def __str__(self):
        return "%s | %s" % (self.nama_bank, self.program)

class Donatur(models.Model):
    nama  = models.CharField(max_length=100)
    email = models.CharField(max_length=100, null=True)
    no_hp = models.CharField(max_length=100, null=True)

class TipeDonasi(models.Model):
    tipe = models.CharField(max_length=1)
    nama = models.CharField(max_length=100, null=True)
    nominal = models.IntegerField()
    program = models.ForeignKey('Program', null=True)

    def __str__(self):
        return "%s | %s" % (self.tipe, self.nominal)

class DonasiDonatur(models.Model):
    kode = models.CharField(max_length=20)
    tanggal = models.DateField()
    bank_yg_dituju = models.ForeignKey(Bank, null=True)
    donatur  = models.ForeignKey(Donatur)
    is_konfirmasi = models.BooleanField(default=False)

class Donasi(models.Model):
    tipe_donasi = models.ForeignKey(TipeDonasi)
    jumlah = models.IntegerField()
    donasi_donatur = models.ForeignKey(DonasiDonatur)
    program = models.ForeignKey('Program', null=True)

    @property
    def total_nominal(self):
        return self.jumlah * self.tipe_donasi.nominal

class Program(models.Model):
    tema = models.CharField(max_length=200)
    tahun = models.CharField(max_length=4, primary_key=True)

    def __str__(self):
        return "%s | %s" % (self.tahun, self.tema)

# Create your models here.
class Pengeluaran(models.Model):
    tanggal = models.DateField()
    keterangan = models.TextField()
    jumlah = models.IntegerField()
    untuk_donasi = models.BooleanField()

# Create your models here.
class Laporan(models.Model):
    posted_time = models.DateTimeField()
    edited = models.BooleanField(default=False)
    title = models.CharField(max_length=500)
    content = models.TextField()
    program = models.ForeignKey('Program', null=True)

    def __str__(self):
       return "%s | %s" % (self.title, self.program)

class Foto(models.Model):
    laporan = models.ForeignKey(Laporan, on_delete=models.CASCADE)
    gambar = models.FileField(upload_to='data/media/foto')
    caption = models.CharField(max_length=500)

ramadhan4kidsapp/views/admin_views.py
__author__ = 'afifun'

import os
import datetime
from datetime import time
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext, Context
from django.utils import timezone
from ramadhan4kidsapp.models import *

@login_required()
def index(request):
    try:
        donasi_list = Donasi.objects.all()
    except Donasi.DoesNotExist:
        donasi_list = None

    data = {'donasi_list': donasi_list}
    return render(request, 'ramadhan4kidsapp/admin/index-admin.html', data)

def upload_laporan(request):
    return  render(request, 'ramadhan4kidsapp/admin/upload-laporan-admin.html')

def laporan_keuangan(request):
    return  render(request, 'ramadhan4kidsapp/admin/laporan-keuangan-admin.html')

def upload_donasi(request):
    if request.method == 'POST':
        namafile = request.FILES['file']
        temp = Temp(filecontent=namafile)
        temp.save()
        path = str(temp.filecontent)
        print(path)
        upload_donasi_excel(path)

        os.remove(path)
        temp.delete()

    return  render(request, 'ramadhan4kidsapp/admin/upload-data-donasi.html')

def upload_donasi_excel(path):
    b = xlrd.open_workbook(path)
    sheet = b.sheet_by_index(0)
    nrows = sheet.nrows
    ncols = sheet.ncols

    for r in range(4, nrows):
        tanggal 		 = sheet.cell_value(r,2)
        print(tanggal)
        tanggal 	     = datetime.datetime.utcfromtimestamp((tanggal - 25569) * 86400.0).strftime('%Y-%m-%d')
        nama 	         = sheet.cell_value(r,3)
        email 	         = sheet.cell_value(r,4)
        paket 	         = sheet.cell_value(r,5).lower()

        print (paket)
        pembagi = 100
        if paket == 'a':
            pembagi = 50
        elif paket == 'b':
            pembagi = 100
        elif paket == 'c':
            pembagi =150
        else:
            raise Exception

        jumlah_paket     = sheet.cell_value(r,6) / pembagi

        bank             = sheet.cell_value(r,7)
        no_hp 	         = sheet.cell_value(r,8)

        donatur = Donatur(nama=nama,email=email, no_hp=no_hp)
        donatur.save()
        millis = int(round(time.time() * 1000))
        donasi_donatur = DonasiDonatur(kode=str(millis), tanggal=tanggal, donatur=donatur)
        donasi_donatur.save()

        tipe_donasi = TipeDonasi.objects.get(tipe=paket)
        donasi = Donasi(tipe_donasi=tipe_donasi, jumlah=jumlah_paket, donasi_donatur=donasi_donatur)

        donasi.save()

def laporan_keuangan(request):
    pengeluaran = Pengeluaran.objects.all()
    data = {'pengeluaran_list':pengeluaran, 'total_pengeluaran': get_total_pengeluaran()}
    return render(request, 'ramadhan4kidsapp/admin/laporan-keuangan-admin.html', data)
def upload_pengeluaran_excel(request):

    if request.method == 'POST':
        namafile = request.FILES['file']
        temp = Temp(filecontent=namafile)
        temp.save()
        path = str(temp.filecontent)
        print(path)
        upload_excel(path)

        os.remove(path)
        temp.delete()

    # path = str(temp.filecontent)

    return  render(request, 'ramadhan4kidsapp/admin/upload-laporan-admin.html')

def upload_excel(path):
    b = xlrd.open_workbook(path)
    sheet = b.sheet_by_index(0)
    nrows = sheet.nrows
    ncols = sheet.ncols

    for r in range(4, nrows):
        tanggal 		 = sheet.cell_value(r,1)
        tanggal 	     = datetime.datetime.utcfromtimestamp((tanggal - 25569) * 86400.0).strftime('%Y-%m-%d')
        nominal 	     = sheet.cell_value(r,2)
        keterangan 	     = sheet.cell_value(r,3)

        untuk_donasi    = False
        if sheet.cell_value(r,4) == 1:
            untuk_donasi = True

        tuple = (tanggal,nominal,keterangan,untuk_donasi)
        print (tuple)

        pengeluaran      = Pengeluaran(tanggal=tanggal,keterangan=keterangan,jumlah=nominal,untuk_donasi=untuk_donasi)
        pengeluaran.save()

def get_total_pengeluaran():
    list_pengeluaran = Pengeluaran.objects.all()
    total = 0
    for item in list_pengeluaran:
        if item.jumlah != None:
            total += item.jumlah
    return total

def get_saldo():
    return get_pemasukan_value() - get_pengeluaran_value()

# Create your views here.
def laporan_list(request):
    laporan_list = Laporan.objects.all()
    return render(request, 'ramadhan4kidsapp/admin/laporan-list.html', {'laporan_list':laporan_list})

def add_laporan(request):
    data = {}
    if request.method == 'POST':
        program = request.POST.get('program')
        judul = request.POST.get('judul')
        content = request.POST.get('konten')
        foto_list = request.FILES.getlist('foto')
        caption_list = request.POST.getlist('caption')

        program_obj = Program.objects.get(pk=program)

        laporan = Laporan(program=program_obj,title=judul, content=content, posted_time=timezone.now())
        laporan.save()
        for i,foto in enumerate(foto_list):
            foto = Foto(laporan=laporan,gambar=foto, caption=caption_list[i])
            foto.save()
    else:
        # initialize program choice form
        data.update({'programs' : Program.objects.all().order_by('-tahun')})

    return render(request, 'ramadhan4kidsapp/admin/laporan-add.html', data)

def edit_laporan(request,id):

    data = {}
    if request.method == 'POST':
        judul = request.POST.get('judul')
        content = request.POST.get('konten')
        foto_list = request.FILES.getlist('foto')
        caption_list = request.POST.getlist('caption')
        delete_foto_list = request.POST.getlist('id-foto')

        laporan = Laporan.objects.get(id=id)
        laporan.title = judul
        laporan.content = content
        laporan.edited = True
        laporan.posted_time = timezone.now()

        laporan.save()
        for i,foto in enumerate(foto_list):
            foto = Foto(laporan=laporan,gambar=foto, caption=caption_list[i])
            foto.save()

        if delete_foto_list:
            for id in delete_foto_list:
                foto = Foto.objects.get(id=id)
                foto.delete()

    else:
        laporan = Laporan.objects.get(id=id)
        data = {'laporan': laporan}

    return render(request, 'ramadhan4kidsapp/admin/laporan-edit.html', data)

def kirim_lpj(request):
    donatur         = Donatur.objects.all()

    d               = Context({'host': '{{ host }}', 'nama_donatur':'{{ nama_donatur }}' } )

    email_subject   = "Laporan Pertanggung Jawaban Ramadhan For Kids"

    data            = {'subjek': email_subject, 'donatur': donatur, 'nama_donatur':'{{ nama_donatur }}'}

    if request.method == 'POST':
        email_list      = []
        email_list_clr  = []
        email_fail      = ''
        success_count   = 0
        try:

            email_subject   = request.POST.get('subjek')
            email_donatur   = request.POST.get('alamat_email')
            email_lainnya   = request.POST.get('email_lainnya')
            attach          = request.FILES['file']


            if(request.POST.get('kirim') == '1'):
                email_all_donatur = []
                for d in donatur:
                    email_all_donatur.append(d.email)
                email_list = email_all_donatur
            else :
                if not validator.is_empty(email_donatur):
                    email_donatur_list = email_donatur.split(";")
                    email_list += email_donatur_list

            if not validator.is_empty(email_lainnya):
                email_lainnya_list   = email_lainnya.split(";")
                email_list          += email_lainnya_list

            txt_content     = request.POST.get('pesan')
            text_file       = open(settings.PROJECT_PATH + "/data/template/temp.html", "w", encoding='utf-8')
            text_file.write(txt_content)
            text_file.close()


            for e in email_list:
                if (not validator.is_empty(e)) and validator.is_email(e):
                    email_list_clr.append(e)

            for e in email_list_clr:
                email   = []
                e       = e.strip()
                if (not validator.is_empty(e)) and validator.is_email(e):
                    email.append(e)

                    nama = ""
                    try:
                        donatur_p   = get_object_or_404(Donatur, email=e)
                        nama        = donatur_p.nama
                    except Exception as e:
                        print(e)

                    d_temp               = Context({'nama_donatur': nama,'program': program, 'host': 'http://localhost:8000', 'donasi': donasi, 'rekening': rekening})
                    template_html_temp   = get_template("temp.html")
                    html_content_temp    = template_html_temp.render(d_temp)
                    # msg                  = EmailMultiAlternatives(email_subject, html_content_temp, 'moh.afifun@ui.ac.id', email)
                    # msg.attach_alternative(html_content_temp, "text/html")
                    msg                  = EmailMessage(email_subject, html_content_temp, 'moh.afifun@ui.ac.id', email, headers={'From': 'beribuku@gmail.com'})
                    msg.content_subtype  = "html"

                    if attach != None:
                        msg.attach(attach.name, attach.read(), attach.content_type)

                    print(email)
                    msg.send()
                    print('sukses')
                    success_count  += 1
                else:
                    email_fail     += e + ','
                print('kosong')

        except Exception as e:
            print(e)

        gagal = len(email_list_clr)-success_count

        print(str(success_count))
        print(str(gagal))
        print(str(len(email_list_clr)))

ramadhan4kidsapp/templates/ramadhan4kidsapp/admin/base.html
{% load static %}
<html>
<head>
	<title>Admin</title>

	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-admin-theme.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap-admin-theme-change-size.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery.easy-pie-chart.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery.easy-pie-chart_custom.css' %}">

	<link rel="stylesheet" href="{% static 'css/style-admin.css' %}">
	<link rel="stylesheet" href="http://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.css">
	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
	<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.js"></script>
	<script type="text/javascript" src="http://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.js"></script>
	<script type="text/javascript">var switchTo5x=true;</script>
	<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
	<script type="text/javascript">stLight.options({publisher: "1df9b28e-9bb1-46a7-9e87-f19ff970f804", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

	<script>
		$(document).ready( function () {
		    $('#table_id').DataTable({
			    "iDisplayLength": 5,
			    "aLengthMenu":[5,10,25,50,100]
			  } );
		} );
	</script>
</head>

<body class="bootstrap-admin-with-small-navbar fontOpen">
	<div class="frame" style="margin-top:-30px">
		<!-- small navbar -->
        <nav class="navbar navbar-default navbar-fixed-top bootstrap-admin-navbar-sm" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    
                    <ul class="nav navbar-nav navbar-right">                        
                        <li class="dropdown">
                            <a href="#" role="button" class="dropdown-toggle" data-hover="dropdown"> <i class="glyphicon glyphicon-user"></i> Admin <i class="caret"></i></a>
                            <ul class="dropdown-menu">                                                                
                                <li><a href="/admin/logout/">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <!-- left, vertical navbar & content -->
            <div class="row">
                <!-- left, vertical navbar -->

                <div class="col-md-2 bootstrap-admin-col-left">

                    <ul class="nav navbar-collapse collapse bootstrap-admin-navbar-side">
                    	<a href=""><img src="{% static 'img/logo.png' %}" class="img-table"></a>
                        <li class="">
                            <a href="{% url 'ramadhan4kidsapp:admin.index' %}"><i class="glyphicon glyphicon-chevron-right"></i> Daftar Donasi</a>
                        </li>
                        <li class="">
                            <a href="{% url 'ramadhan4kidsapp:admin.upload_laporan' %}"><i class="glyphicon glyphicon-chevron-right"></i> Upload Laporan</a>
                        </li>
                        <li class="">
                            <a href="{% url 'ramadhan4kidsapp:admin.upload.donasi' %}"><i class="glyphicon glyphicon-chevron-right"></i> Upload Data Donasi</a>
                        </li>
                        <li class="">
                            <a href="{% url 'ramadhan4kidsapp:admin.laporan_keuangan' %}"><i class="glyphicon glyphicon-chevron-right"></i> Keuangan</a>
                        </li>

                        <li class="">
                            <a href="{% url 'ramadhan4kidsapp:admin.laporan_list' %}"><i class="glyphicon glyphicon-chevron-right"></i> Daftar Laporan</a>
                        </li>

                        <li class="">
                            <a href="{% url 'ramadhan4kidsapp:admin.kirim.lpj' %}"><i class="glyphicon glyphicon-chevron-right"></i> Kirim LPJ</a>
                        </li>

                        <li class="">
                            <a href="/admin/ramadhan4kidsapp/program/"><i class="glyphicon glyphicon-chevron-right"></i>Daftar Program</a>
                        </li>

                    </ul>
                </div>

        {% block content %}{% endblock %}

                <!-- footer -->
{% load static %}
            </div>
            </div>
        </div>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/twitter-bootstrap-hover-dropdown.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap-admin-theme-change-size.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.easy-pie-chart.js' %}"></script>
        <div class="navbar navbar-footer">
            <div class="container">
                <div class="row">
                    <footer role="contentinfo" >
                        <p class="left">Ramadhan For Kids</p>
                        <p class="right">&copy; 2015 <a href="http://rse.cs.ui.ac.id" target="_blank" style="color:black">FMSE, Lab.</a></p>
                    </footer>
                </div>
            </div>
</body>
</html>

ramadhan4kidsapp/templates/ramadhan4kidsapp/admin/footer-admin.html
<!-- footer -->
{% load static %}

{#<script src="{% static 'js/jquery.js' %}"></script>#}
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/twitter-bootstrap-hover-dropdown.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-admin-theme-change-size.js' %}"></script>        
<script type="text/javascript" src="{% static 'js/jquery.easy-pie-chart.js' %}"></script>     
        <div class="navbar navbar-footer">
            <div class="container">
                <div class="row">
                    <footer role="contentinfo" >
                        <p class="left">Ramadhan For Kids</p>
                        <p class="right">&copy; 2015 <a href="http://rse.cs.ui.ac.id" target="_blank" style="color:black">RSE Lab, Fasilkom UI.</a></p>
                    </footer>
                </div>
            </div>
        </div>

ramadhan4kidsapp/templates/ramadhan4kidsapp/admin/laporan-edit.html
{% extends  'ramadhan4kidsapp/admin/base.html' %}
{% load static %}
{% load currencytag %}

{% block content %}
	<div class="col-md-10">
		<div class="row">
			<div class="page-header bootstrap-admin-content-title">
				<h2>Upload Data Donasi
					</h2>

				<a href="{% url 'admin.index' %}" class="action">
					<button class="btn btn-sm btn-default">
						<i class="glyphicon glyphicon-chevron-left"></i>
						Back
					</button>
				</a>
			</div>
		</div>

		<div class="row">
			<div class="panel panel-default bootstrap-admin-no-table-panel">
				<div class="panel-heading">
					<div class="text-muted bootstrap-admin-box-title"> <span class="glyphicon glyphicon-upload"></span>  &nbsp;Upload Data Donasi Disini </div>

				</div>
				<div class="bootstrap-admin-panel-content bootstrap-admin-no-table-panel-content collapse in">


		<div class="admin-content">
			<div class="newprogram">
				<div class="container" style="width:100%">

					<form action="" class="form-horizontal" role="form" method="post" enctype="multipart/form-data">{% csrf_token %}
						{% if alert_success %}
							<div class="form-group">
								<label for="inputPassword3" class="col-sm-2 control-label"></label>
						    	<div class="col-sm-10">
						    		<div class="alert alert-{% if alert_success %}success{% else %}danger{% endif %} alert-dismissible" role="alert">
	  								<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{% autoescape on %}{{ alert_msg }}{% endautoescape %}</div>
						    	</div>
							</div>
						{% endif %}

					  	<div class="form-group">
					    	<label for="inputPassword3" class="col-sm-2 control-label">Judul</label>
					    	<div class="col-sm-10">
					    		<input type="text" class="form-control" name="judul" value="{{ laporan.title }}" placeholder="" required>
					    	</div>
					  	</div>
                        <div class="form-group">
					    	<label for="inputPassword3" class="col-sm-2 control-label">Konten</label>
					    	<div class="col-sm-10">
					    		<textarea class="form-control" id="konten" name="konten" style="100%">{{ laporan.content|safe }}</textarea>
					    	</div>
					  	</div>


                        <div class="form-group">
					    	<label for="inputPassword3" class="col-sm-2 control-label"></label>
					    	<div class="col-sm-10">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Gambar</th>
                                <th>Hapus</th>
                            </tr>
                            </thead>
                            <tbody style="height: 300px;overflow-y: scroll;">
                                {% for foto in laporan.foto_set.all %}
                                    <tr>
                                        <td><img style="height:100px;width:100px" src="../../../{{ foto.gambar }}" alt=""></td>
                                        <td class="filterable-cell"><input name="id-foto" value="{{ foto.id }}" type="checkbox"></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                    </table>
                    </div>
					  	</div>
						<div class="form-group">
							<label for="inputPassword3" class="col-sm-2 control-label">Gambar</label>
							<div class="col-sm-10 div-gambar">
								<div class="row">
									<div class="col-sm-3">
										<input type="file" class="form-control" name="foto" id="" placeholder="">
											<p class="help-block">Unggah file gambar dengan jenis jpg, png, atau gif</p>
									</div>

									<div class="col-sm-9">
										<input type="text" class="form-control" name="caption" id="" placeholder="Keterangan gambar (opsional)">
									</div>
								</div>
							</div>
							<br><br>
							<div class="col-sm-offset-2 col-sm-10">
								<div class="btn btn-success btn-gambar">tambah gambar</div>
							</div>
						</div>

					  	<div class="form-group">
					    	<div class="col-sm-offset-2 col-sm-10">
					      		<button type="submit" class="btn btn-primary">Upload</button>
					    	</div>
					  	</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
		</div>
		<script type="text/javascript">


	tinymce.init({
		selector: "#konten",
		theme: "modern",
		plugins: [
			"advlist autolink lists link image charmap print preview hr anchor pagebreak",
			"searchreplace wordcount visualblocks visualchars code fullscreen",
			"insertdatetime media nonbreaking save table contextmenu directionality",
			"emoticons template paste textcolor colorpicker textpattern image"
		],
		toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
		toolbar2: "print preview media | forecolor backcolor emoticons",
		image_advtab: true,
		templates: [
			{title: 'Test template 1', content: 'Test 1'},
			{title: 'Test template 2', content: 'Test 2'}
		]
    });
	tinymce.get('#konten').focus();
	tinymce.triggerSave();
</script>
		{% endblock %}